<?php

return [
    'whatsapp' => env('WHATSAPP_ADMIN_NUMBER', '6281385434382'),
    'company' => [
        'company_name' => env('COMPANY_NAME', 'Novastra'),
        'brand_suffix' => env('COMPANY_BRAND_SUFFIX', 'Global Supply'),
        'legal_name' => env('COMPANY_LEGAL_NAME', 'CV Novastra Global Supply'),
        'tagline' => env('COMPANY_TAGLINE', 'Supplying quality, delivering trust.'),
        'business_summary' => env('COMPANY_SUMMARY', 'Pengadaan dan distribusi bahan pangan untuk rumah, bisnis, dapur, katering, industri, dan institusi.'),
        'nib' => env('COMPANY_NIB', '2402260050323'),
        'nib_issued_at' => env('COMPANY_NIB_ISSUED_AT', '24 Februari 2026'),
        'legal_status' => env('COMPANY_LEGAL_STATUS', 'PMDN · Usaha Mikro'),
        'location' => env('COMPANY_LOCATION', 'Cisauk, Kabupaten Tangerang, Banten'),
        'email' => env('COMPANY_EMAIL', 'cvnovastraglobalsupply@gmail.com'),
        'phone' => env('COMPANY_PHONE', '0813-8543-4382'),
        'whatsapp' => env('WHATSAPP_ADMIN_NUMBER', '6281385434382'),
        'operating_hours' => env('COMPANY_OPERATING_HOURS', 'Senin-Sabtu, 09.00-17.00'),
        'hero_eyebrow' => env('COMPANY_HERO_EYEBROW', 'Bahan pangan & kebutuhan dapur'),
        'hero_title' => env('COMPANY_HERO_TITLE', 'Pasokan yang baik dimulai dari bahan yang tepat.'),
        'hero_description' => env('COMPANY_HERO_DESCRIPTION', 'Ayam, ikan, sayur, buah, bumbu, dan kebutuhan pangan pilihan untuk rumah maupun operasional bisnis.'),
        'show_testimonials' => env('SHOW_TESTIMONIALS', true) ? '1' : '0',
        'show_faq' => env('SHOW_FAQ', true) ? '1' : '0',
    ],
    'customer' => [
        'username' => env('CUSTOMER_USERNAME', 'pelanggan'),
        'password' => env('CUSTOMER_PASSWORD'),
        'name' => env('CUSTOMER_NAME', 'Pelanggan Novastra'),
        'email' => env('CUSTOMER_EMAIL', 'pelanggan@example.com'),
    ],
    'admin' => [
        'username' => env('ADMIN_USERNAME', 'admin'),
        'password' => env('ADMIN_PASSWORD'),
        'password_hash' => env('ADMIN_PASSWORD_HASH'),
        'email' => env('ADMIN_EMAIL', 'admin@example.com'),
    ],
    'public_upload_dir' => env('PUBLIC_UPLOAD_DIR') ?: public_path('uploads'),
    'private_upload_dir' => env('PRIVATE_UPLOAD_DIR') ?: storage_path('app/private'),
    'temp_upload_dir' => env('TEMP_UPLOAD_DIR') ?: storage_path('app/tmp'),
];
